import 'codemirror/lib/codemirror.css';
import 'codemirror/mode/python/python.js';
import 'codemirror/addon/hint/show-hint';
import 'codemirror/addon/display/autorefresh';
import 'codemirror/theme/abcdef.css';
import 'codemirror/theme/darcula.css';
import 'codemirror/theme/idea.css';
import type { Options } from './options';
import type { IThebeCell } from 'thebe-core';
import type { CellDOMPlaceholder } from './types';
export declare function setupCodemirror(options: Options, item: CellDOMPlaceholder, cell: IThebeCell, cellEl: HTMLElement, editorEl: HTMLElement, setBusy: (id: string) => void, clearBusy: (id: string) => void): any;
